//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominios
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoPessoas
    {
        public TipoPessoas()
        {
            this.Pessoas = new HashSet<Pessoas>();
        }
    
        public int id { get; set; }
        public string Nome { get; set; }
    
        public virtual ICollection<Pessoas> Pessoas { get; set; }
    }
}
